### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by AllenLyu** [wangyufeng0615/bjuthelper#1]
对于你所说的php，html互相嵌入不是很优雅的问题，我想你可以这样做：
1. 使用框架，或者自己动手写一个微型的MVC分层，这样会比较美观；
2. 将查询做成一个服务，用于返回json格式的数据，这样也可以做到前后端代码分离，而且会更美观:-)

**Comment by wangyufeng0615** [comment]
非常感谢！

**Comment by AllenLyu** [comment]
我只是偶尔搜学校名字发现了有人在搞这个东西

**Comment by AllenLyu** [comment]
用Python写爬虫会优雅很多，不但有request库，还有一些库支持css选择器，而且还会有库支持图片识别。你可以考虑用Python写一个进程来分析这些，然后php与这个端口进行通讯，变着花样的玩:-)
